#!/usr/bin/env bash
#bash scrpt that gives you information about the school file.

FILE=alxschool
if [ -e $FILE ]; then
   echo "$FILE file exists"
   if [ -s $FILE ]; then
      echo "$FILE file is not empty"
   else
      echo "$FILE file is empty"
   fi
   if [ -f $FILE ]; then
      echo "$FILE file is regular file"
   fi
else
   echo "$FILE file doesnt exit"
fi



